In [12]:
def encrypt_hill_cipher(a,key):
    a = a.dot(key)
    result = ""
    for i in a:
            for j in i:
                result += chr(j%26 + 65)
    return result

In [13]:
def decrypt_hill_cipher(a,key):
    a = a.dot(key)
    result = ""
    for i in a:
        for j in i:
            result += chr(j%26+65)
    result = result.replace('Z','')
    return result

In [14]:
def multiplicative_inverse(a,mod_key) : 
    m,m0,y,x = mod_key,mod_key,0,1 
    while (a>1) :
        if(m==0):
            return -1;
        q = a//m 
        t = m 
        m = a%m 
        a = t 
        t = y 
        y = x - q * y 
        x = t 
    if (x<0): 
        x = x + m0   
    return x 

In [20]:
import numpy as np
import math
from sympy import Matrix

#key = np.array([[3,4,7,1],[1,2,4,6],[10,7,5,15],[13,16,11,2]])
key = np.array([[3,5,7],[1,4,13],[2,7,3]])
print(key)
key_length = key.shape[0];
PlainText = "Hill Cipher uses matrix multiplication using inverse to encrypt and decrypt"
#PlainText = 'Product based jobs'
PlainText = PlainText.replace(" ",'').upper()
n = len(PlainText)

if(n%4 != 0):
    dump = key_length - len(PlainText)%key_length
    for i in range(dump):
        PlainText += 'Z'
print(PlainText)

plaintext = np.array([ord(i)-65 for i in PlainText])
plaintext = np.reshape(plaintext,(-1,key_length))
encrypted_message = encrypt_hill_cipher(plaintext,key)
print('The encrypted message is " ',encrypted_message,' "')
encrypted_text = np.array([ord(i)-65 for i in encrypted_message])
encrypted_text = np.reshape(encrypted_text,(-1,key_length))

encrypted = np.array([ord(i)-65 for i in encrypted_message])
encrypted = np.reshape(encrypted,(-1,key_length))
determinant = np.linalg.det(key)
determinant = int(round(determinant))
print('The determinant is ',determinant)
mod_key = 16

a = Matrix(key).inv_mod(mod_key)
x = multiplicative_inverse(determinant%mod_key,mod_key)
list1 = np.array([round((i*determinant*x)%mod_key) for i in a])
list1 = np.reshape(list1,(key_length,key_length))
print(list1)
print(list1.dot(key))

decrypted_message = decrypt_hill_cipher(encrypted_text,list1)
print('The decrypted message is " ',decrypted_message,' "')



[[ 3  5  7]
 [ 1  4 13]
 [ 2  7  3]]
HILLCIPHERUSESMATRIXMULTIPLICATIONUSINGINVERSETOENCRYPTANDDECRYPTZ
The encrypted message is "  ZOEZPXIBADFRCUMBNMTIBFRCJVYAWEPRTRLPXEJBFCNGRHMFDIVBAIFEQUDUTMVKOL  "
The determinant is  -129
[[15 14 11]
 [9 5 0]
 [1 11 9]]
[[81 208 320]
 [32 65 128]
 [32 112 177]]
The decrypted message is "  LWNCONKDUEOAAODPUFKWVVKBDUYKHKYFQKAWKJDGJKKFSIBOXYFXGRJVKYLIBTB  "
